### ISSUE TITLE
[Task] Backend fixes and feautres

### ISSUE THREAD

**Issue by SalahAdDin** [JensAstrup/django-jetpack#25]
Here have a home works list:

- [ ] Fix custom filters field testing. https://github.com/JensAstrup/django-jetpack/issues/24
- [ ] Solve travis ci error. https://github.com/JensAstrup/django-jetpack/issues/22
- [ ] App label problem. https://github.com/JensAstrup/django-jetpack/issues/17
